Fix QNAP package. Cannot use newer versions of fast-xml-parser dependency to no longer working with older versions of node.
ERROR:

/share/CACHEDEV1_DATA/.qpkg/filebot-node/server/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:1
(function (exports, require, module, __filename, __dirname) { const { buildOptions} = require("./OptionsBuilder");
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/share/CACHEDEV1_DATA/.qpkg/filebot-node/server/node_modules/fast-xml-parser/src/fxp.js:4:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)